"""SEO metadata for blog articles — enriches blog_data.ARTICLES without touching content.

Provides hero images (locally generated by Nano Banana — see scripts/generate_blog_images.py),
author, dates, canonical URLs, FAQ entries for rich snippets, and Open Graph fields.
Merged into each article by server.py.
"""

SITE_URL = "https://mwana-lingala.com"
# Relative paths so images work in BOTH preview env and production (resolved by browser
# against the current origin). For OG/Schema.org meta tags we prepend SITE_URL in the frontend.
LOCAL_IMG = "/images/blog"

DEFAULT_AUTHOR = {
    "name": "L'équipe Mwana Lingala",
    "role": "Linguistes & parents de la diaspora congolaise",
    "picture": f"{SITE_URL}/images/icon-512.png",
    "url": SITE_URL,
}

# Maps blog slug → SEO metadata. Hero images are PNG files generated locally with
# the Nano Banana model (panafrican children-book illustration style, matching homepage).
META = {
    "je-t-aime-en-lingala": {
        "hero_image": f"{LOCAL_IMG}/je-t-aime-en-lingala.png",
        "hero_image_alt": "Famille congolaise tendre — illustration sur la transmission de l'amour en Lingala (Nalingi yo)",
        "published_at": "2026-04-12T09:00:00Z",
        "updated_at": "2026-05-03T00:00:00Z",
        "faq": [
            {"q": "Comment dit-on « Je t'aime » en Lingala ?", "a": "« Je t'aime » en Lingala se dit Nalingi yo, prononcé na-LIN-gi yo."},
            {"q": "Que veut dire Bolingo ?", "a": "Bolingo est le mot Lingala pour « l'amour ». On dit Bolingo ya solo (amour vrai) ou Nazali na bolingo na yo (j'ai de l'amour pour toi)."},
            {"q": "Comment dire « Je t'aime, mon enfant » en Lingala ?", "a": "On dit Nalingi yo mwana na ngai — c'est l'expression la plus tendre pour un parent."},
            {"q": "Comment dire « Tu me manques » en Lingala ?", "a": "On dit Nazali kokanisa yo, qui veut littéralement dire « Je pense à toi »."},
        ],
    },
    "bonjour-en-lingala": {
        "hero_image": f"{LOCAL_IMG}/bonjour-en-lingala.png",
        "hero_image_alt": "Deux amis africains se saluent — Mbote, le « Bonjour » lingala — illustration panafricaine",
        "published_at": "2026-04-10T09:00:00Z",
        "updated_at": "2026-05-03T00:00:00Z",
        "faq": [
            {"q": "Comment dit-on « Bonjour » en Lingala ?", "a": "« Bonjour » en Lingala se dit Mbote, prononcé m-BO-té."},
            {"q": "Comment dire « Merci » en Lingala ?", "a": "« Merci » en Lingala se dit Mercí ou Natondi yo (forme traditionnelle)."},
            {"q": "Comment dire « Au revoir » en Lingala ?", "a": "« Au revoir » se dit Tokomonana (« on se revoit ») ou simplement Kende malamu (« bon voyage »)."},
            {"q": "Comment dire « Comment ça va ? » en Lingala ?", "a": "On dit Ozali malamu ? — la réponse typique est Nazali malamu (« je vais bien »)."},
        ],
    },
    "traduction-francais-lingala-guide": {
        "hero_image": f"{LOCAL_IMG}/traduction-francais-lingala-guide.png",
        "hero_image_alt": "Dictionnaire bilingue français-lingala ouvert — illustration panafricaine pour apprenants",
        "published_at": "2026-04-08T09:00:00Z",
        "updated_at": "2026-05-03T00:00:00Z",
        "faq": [
            {"q": "Existe-t-il un traducteur français-lingala en ligne gratuit ?", "a": "Oui, l'outil gratuit Mwana Lingala Traduction permet de traduire en un clic, avec audio natif et exemples."},
            {"q": "Le Lingala a-t-il un alphabet ?", "a": "Le Lingala utilise l'alphabet latin avec 7 voyelles (a, e, ɛ, i, o, ɔ, u) et emprunte la notation française dans la pratique courante."},
            {"q": "Combien de mots faut-il connaître pour parler Lingala ?", "a": "Avec 500 mots de vocabulaire, on peut tenir 90 % des conversations quotidiennes. Mwana Lingala propose 87 mots essentiels pour démarrer."},
        ],
    },
    "apprendre-lingala-enfant": {
        "hero_image": f"{LOCAL_IMG}/apprendre-lingala-enfant.png",
        "hero_image_alt": "Parent congolais lisant un livre lingala à son enfant — transmission familiale, illustration douce",
        "published_at": "2026-04-05T09:00:00Z",
        "updated_at": "2026-05-03T00:00:00Z",
        "faq": [
            {"q": "À quel âge apprendre le Lingala à son enfant ?", "a": "Dès la naissance ! Le cerveau d'un bébé distingue les sons de toutes les langues jusqu'à 1 an. Plus vous commencez tôt, meilleur sera l'accent natif."},
            {"q": "Combien de temps par jour ?", "a": "5 à 10 minutes quotidiennes suffisent. La régularité compte plus que la durée."},
            {"q": "Mon enfant ne parle que français, est-ce trop tard ?", "a": "Non ! Entre 4 et 10 ans, l'enfant apprend encore très vite une 2ème langue. Mwana Lingala propose un parcours progressif adapté à chaque âge."},
        ],
    },
    "mots-lingala-indispensables": {
        "hero_image": f"{LOCAL_IMG}/mots-lingala-indispensables.png",
        "hero_image_alt": "Tableau coloré de mots lingala essentiels — illustration vocabulaire panafricaine pour débutants",
        "published_at": "2026-04-02T09:00:00Z",
        "updated_at": "2026-05-03T00:00:00Z",
        "faq": [
            {"q": "Quels sont les 10 mots Lingala les plus utiles ?", "a": "Mbote (bonjour), Mercí (merci), Yo (toi), Ngai (moi), Mama (maman), Tata (papa), Ndako (maison), Mai (eau), Bilei (nourriture), Malamu (bien)."},
            {"q": "Peut-on apprendre le Lingala seul ?", "a": "Oui, surtout avec une app comme Mwana Lingala qui donne audio natif, quiz et exemples en contexte."},
        ],
    },
    "apprendre-le-lingala-guide-debutant": {
        "hero_image": f"{LOCAL_IMG}/apprendre-le-lingala-guide-debutant.png",
        "hero_image_alt": "Adulte apprenant le lingala avec carnet et application audio — guide complet débutant 2026",
        "published_at": "2026-05-01T09:00:00Z",
        "updated_at": "2026-05-03T00:00:00Z",
        "faq": [
            {"q": "Combien de temps pour parler lingala couramment ?", "a": "Avec 5 minutes par jour et une méthode structurée, vous atteignez le niveau A2 (conversation simple) en 6 mois. En 12 mois, vous tenez 80 % des conversations quotidiennes."},
            {"q": "Le lingala est-il difficile à apprendre pour un francophone ?", "a": "Non, le lingala est l'une des langues bantoues les plus accessibles : alphabet latin, prononciation régulière, et de nombreux mots empruntés au français (mercí, eskolo, ofisi…)."},
            {"q": "Combien de mots faut-il connaître pour parler lingala ?", "a": "50 mots couvrent 80 % des conversations quotidiennes. 200 mots vous permettent de tenir une vraie conversation. Mwana Lingala propose 87 mots essentiels avec audio natif."},
            {"q": "Comment apprendre le lingala gratuitement ?", "a": "Plusieurs ressources gratuites existent : l'app Mwana Lingala (20 mots offerts), Wikipedia Lingala, YouTube communautaire, et le traducteur français-lingala instantané sur mwana-lingala.com."},
        ],
    },
    "comment-apprendre-lingala-enfant": {
        "hero_image": f"{LOCAL_IMG}/comment-apprendre-lingala-enfant.png",
        "hero_image_alt": "Père et fille riant pendant qu'ils apprennent le lingala à la maison — illustration douce, panafricaine",
        "published_at": "2026-04-28T09:00:00Z",
        "updated_at": "2026-05-03T00:00:00Z",
        "faq": [
            {"q": "À quel âge commencer à apprendre le lingala à son enfant ?", "a": "Dès la naissance idéalement. Le cerveau d'un bébé distingue tous les sons de toutes les langues jusqu'à 12 mois. Mais il n'est jamais trop tard : entre 4 et 10 ans, l'enfant apprend très vite une 2ème langue."},
            {"q": "Mon enfant ne parle que français — c'est trop tard ?", "a": "Non, absolument pas. À 7 ans, votre enfant peut encore atteindre un excellent niveau en 12 mois avec 5 min/jour. L'accent natif est plus difficile, mais l'identité culturelle prime."},
            {"q": "Combien de temps par jour faut-il dédier au lingala ?", "a": "5 minutes suffisent — la régularité bat la durée. Une étude de l'université de l'Oregon prouve que 5 min/jour est plus efficace que 2h une fois par semaine."},
            {"q": "Que faire si je ne parle pas bien lingala moi-même ?", "a": "Apprenez avec votre enfant : c'est la méthode la plus efficace ! Utilisez les audios natifs de Mwana Lingala pour combler vos lacunes, et faites parler les grands-parents par WhatsApp."},
        ],
    },
    "histoire-du-lingala-origine-evolution": {
        "hero_image": f"{LOCAL_IMG}/histoire-du-lingala-origine-evolution.png",
        "hero_image_alt": "Fleuve Congo et pirogue traditionnelle au coucher du soleil — berceau historique du lingala",
        "published_at": "2026-04-25T09:00:00Z",
        "updated_at": "2026-05-03T00:00:00Z",
        "faq": [
            {"q": "Qui parle lingala dans le monde aujourd'hui ?", "a": "Plus de 45 millions de personnes : 30 millions en RDC, 5 millions au Congo-Brazzaville, et 3 millions dans la diaspora (France, Belgique, USA, Canada, Afrique du Sud)."},
            {"q": "Le lingala est-il une langue bantoue ?", "a": "Oui, le lingala fait partie de la famille bantoue, qui compte plus de 500 langues parlées en Afrique subsaharienne. Il dérive principalement du bobangi, langue des pêcheurs du fleuve Congo."},
            {"q": "Pourquoi le lingala est devenu si populaire ?", "a": "Trois raisons : (1) la rumba congolaise des années 1960 l'a popularisé en Afrique entière, (2) l'armée coloniale puis l'Église l'ont diffusé à Kinshasa, (3) sa prononciation régulière le rend facile à apprendre."},
        ],
    },
    "compter-en-lingala-chiffres-1-100": {
        "hero_image": f"{LOCAL_IMG}/compter-en-lingala-chiffres-1-100.png",
        "hero_image_alt": "Enfant congolais comptant sur ses doigts — illustration colorée pour apprendre les chiffres lingala 1 à 100",
        "published_at": "2026-04-22T09:00:00Z",
        "updated_at": "2026-05-03T00:00:00Z",
        "faq": [
            {"q": "Comment dit-on 1 en lingala ?", "a": "« Un » en lingala se dit Moko, prononcé mo-KO."},
            {"q": "Comment construire le nombre 35 en lingala ?", "a": "On dit « Tuku misato na mitano » : tuku misato (30) + na (et) + mitano (5)."},
            {"q": "Pourquoi apprendre à compter en lingala aux enfants ?", "a": "Les chiffres sont les premiers mots utilisables au quotidien (âge, jouets, doigts) et favorisent la mémorisation par associations visuelles. C'est aussi un pont vers les autres langues bantoues (swahili, kikongo)."},
        ],
    },
    "cours-de-lingala-en-ligne": {
        "hero_image": f"{LOCAL_IMG}/cours-de-lingala-en-ligne.png",
        "hero_image_alt": "Apprenant adulte suivant un cours de lingala en ligne avec ordinateur et casque audio — illustration aquarelle panafricaine",
        "published_at": "2026-05-03T09:00:00Z",
        "updated_at": "2026-05-03T09:00:00Z",
        "faq": [
            {"q": "Comment apprendre le lingala en ligne ?", "a": "Avec une application spécialisée comme Mwana Lingala (audio natif, mode famille, 87 mots gratuits), des plateformes de tutorat en visio (Preply, iTalki) ou des cours universitaires en ligne (INALCO)."},
            {"q": "Existe-t-il des cours de lingala gratuits ?", "a": "Oui : Mwana Lingala offre 20 mots gratuits avec audio, plusieurs créateurs YouTube proposent des leçons gratuites, et les associations communautaires offrent souvent une session d'essai sans engagement."},
            {"q": "Combien coûte un cours de lingala particulier ?", "a": "Entre 8 et 25 €/h selon le profil du professeur sur Preply ou iTalki. Comptez 100 à 250 €/an pour des cours en association, et environ 250 €/an à l'INALCO (Paris)."},
            {"q": "Quel est le meilleur cours de lingala pour un enfant ?", "a": "Une app pensée pour l'âge (mode Bébé audio + mode Enfant ludique), associée à la pratique quotidienne avec un parent ou grand-parent natif."},
        ],
    },
    "apprendre-lingala-whatsapp": {
        "hero_image": f"{LOCAL_IMG}/apprendre-lingala-whatsapp.png",
        "hero_image_alt": "Maman congolaise apprenant le lingala via messages vocaux WhatsApp avec sa famille au pays — illustration panafricaine",
        "published_at": "2026-05-03T10:00:00Z",
        "updated_at": "2026-05-03T10:00:00Z",
        "faq": [
            {"q": "Peut-on vraiment apprendre le lingala par WhatsApp ?", "a": "Oui — pour la prononciation et le vocabulaire du quotidien c'est extrêmement efficace, surtout combiné à une app structurée pour la grammaire. La méthode des 30 secondes/jour avec un grand-parent natif fonctionne très bien."},
            {"q": "WhatsApp transcrit-il les vocaux en lingala ?", "a": "Oui, depuis 2024 WhatsApp transcrit automatiquement les messages vocaux en plusieurs langues bantoues (lingala compris pour la plupart des dialectes). À activer dans Paramètres → Discussions → Transcrire."},
            {"q": "Comment trouver quelqu'un pour pratiquer le lingala par WhatsApp ?", "a": "Le mieux : un grand-parent ou cousin natif au pays (RDC, Congo). Sinon, des groupes Facebook de la diaspora ou la communauté Mwana Lingala (espace contributeurs)."},
            {"q": "Quels mots lingala apprendre en premier par WhatsApp ?", "a": "Commencez par les salutations (Mbote, Ozali malamu ?), les mots de la famille (Mama, Tata, Bana) et les questions du quotidien (Olei nini ? — Qu'as-tu mangé ?)."},
        ],
    },
    "lingala-vs-swahili": {
        "hero_image": f"{LOCAL_IMG}/lingala-vs-swahili.png",
        "hero_image_alt": "Carte panafricaine illustrant les zones lingala (RDC) et swahili (Afrique de l'Est) — différences entre les deux langues bantoues",
        "published_at": "2026-05-03T11:00:00Z",
        "updated_at": "2026-05-03T11:00:00Z",
        "faq": [
            {"q": "Quelle est la différence entre le lingala et le swahili ?", "a": "Le lingala est parlé en RDC, Congo et Angola (~45M locuteurs) ; le swahili en Tanzanie, Kenya, Ouganda (~200M locuteurs). Le swahili a une forte influence arabe (40 % du vocabulaire), le lingala une influence française. Les deux sont bantous mais issus de branches différentes."},
            {"q": "Peut-on comprendre le swahili en parlant lingala ?", "a": "Non, ce sont deux langues distinctes. Mais 10 % du vocabulaire de base est similaire (mama, tata, mai/maji) car les deux sont bantoues. Avec une bonne base lingala, vous apprenez le swahili 30 % plus vite ensuite."},
            {"q": "Lequel est le plus facile à apprendre pour un francophone ?", "a": "Le lingala. Il a moins de classes nominales (10 vs 16), une prononciation plus régulière, et 30 % de vocabulaire emprunté au français (mercí, eskolo, ofisi)."},
            {"q": "Lequel apprendre si ma famille est de RDC ?", "a": "Le lingala — c'est la langue véhiculaire de Kinshasa, du fleuve Congo et de la rumba congolaise. Le swahili est seulement parlé dans l'est de la RDC (Goma, Bukavu, Lubumbashi)."},
        ],
    },
    "apprendre-lingala-pdf": {
        "hero_image": f"{LOCAL_IMG}/apprendre-lingala-pdf.png",
        "hero_image_alt": "Manuel de lingala ouvert à côté d'un smartphone affichant des ondes audio — méthode hybride PDF + app moderne",
        "published_at": "2026-05-03T12:00:00Z",
        "updated_at": "2026-05-03T12:00:00Z",
        "faq": [
            {"q": "Existe-t-il un PDF gratuit pour apprendre le lingala ?", "a": "Oui : l'article Wikipedia Lingala (exportable en PDF), la « Méthode pratique de lingala » d'Edema Atibakwa (sur archives universitaires), et de nombreux lexiques d'associations. Mais aucun n'inclut d'audio."},
            {"q": "Pourquoi un PDF ne suffit pas pour apprendre le lingala ?", "a": "Parce que sans audio natif, vous risquez de mal prononcer 70 % des mots. Le lingala a 7 voyelles (dont ɛ et ɔ inexistantes en français) qui se devinent mal à l'écrit. Solution : combinez PDF (référence) + app (audio natif)."},
            {"q": "Quel est le meilleur livre PDF pour apprendre le lingala ?", "a": "« Parlons lingala » de Rogério Goma Mpasi (L'Harmattan) ou « Méthode pratique » d'Edema Atibakwa. Tous deux disponibles en édition imprimée et parfois en PDF académique."},
            {"q": "Mwana Lingala propose-t-il un PDF gratuit ?", "a": "Un guide PDF « 50 mots et phrases lingala essentiels » est en préparation pour 2026. Inscrivez-vous gratuitement sur mwana-lingala.com pour être averti·e en avant-première."},
        ],
    },
    "comment-apprendre-lingala-facilement": {
        "hero_image": f"{LOCAL_IMG}/comment-apprendre-lingala-facilement.png",
        "hero_image_alt": "Jeune femme apprenant le lingala facilement avec smartphone et symboles flottants africains — méthode douce et efficace",
        "published_at": "2026-05-03T13:00:00Z",
        "updated_at": "2026-05-03T13:00:00Z",
        "faq": [
            {"q": "Comment apprendre le lingala facilement et rapidement ?", "a": "10 mots à fond la première semaine + 5 minutes par jour, pas 1 heure par semaine. La régularité bat l'intensité. Combinez app avec audio natif (Mwana Lingala), Post-it dans la maison, et 30 secondes de WhatsApp avec un proche natif."},
            {"q": "Combien de temps pour apprendre le lingala ?", "a": "Avec 5 min/jour : niveau A1 (salutations) en 1 mois, A2 (conversation simple) en 6 mois, B1 (fluide) en 12 mois. Plus vite si vous avez un proche natif avec qui pratiquer chaque jour."},
            {"q": "Comment apprendre à parler lingala couramment ?", "a": "3 leviers : pratique orale quotidienne (WhatsApp ou famille), audio natif intensif (apps + chansons), et acceptation des erreurs (parler imparfaitement vaut mieux que ne pas parler). Le mode Parent de Mwana Lingala intègre des dialogues courants à reproduire."},
            {"q": "Quelle est la méthode la plus rapide pour apprendre le lingala ?", "a": "La méthode hybride : 5 min/jour app + 30 sec/jour WhatsApp avec famille + 1 chanson lingala écoutée par jour. Vous tenez une conversation simple en 4 semaines."},
        ],
    },
}


def enrich_article(article: dict) -> dict:
    """Merge core article dict with SEO metadata for the matching slug."""
    slug = article.get("slug", "")
    extra = META.get(slug, {})
    merged = dict(article)  # shallow copy; content_md stays intact
    # Hero image + alt (fallback to open-graph default)
    merged["hero_image"] = extra.get(
        "hero_image",
        f"{SITE_URL}/images/famille-couple-bebe.png",
    )
    merged["hero_image_alt"] = extra.get(
        "hero_image_alt",
        article.get("title", "Mwana Lingala"),
    )
    merged["published_at"] = extra.get("published_at", "2026-04-01T09:00:00Z")
    merged["updated_at"] = extra.get("updated_at", "2026-05-03T00:00:00Z")
    merged["author"] = extra.get("author", DEFAULT_AUTHOR)
    merged["canonical"] = f"{SITE_URL}/blog/{slug}"
    merged["faq"] = extra.get("faq", [])
    # Derive Open Graph image (use the hero image)
    merged["og_image"] = merged["hero_image"]
    return merged
